package:
  name: narupa-server
  version: {{ NARUPA_BUILD_VERSION }}

build:
  noarch: python
  number: 0

requirements:
  run:
    - narupa-core =={{ NARUPA_BUILD_VERSION }}
    - narupa-openmm =={{ NARUPA_BUILD_VERSION }}
    - narupa-ase =={{ NARUPA_BUILD_VERSION }}
    - narupa-mdanalysis =={{ NARUPA_BUILD_VERSION }}

about:
  home: https://narupa.readthedocs.io
  license: GPL-3
  license_file: {{ NARUPA_LICENSE_PATH }}
  summary: Python servers for Narupa.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation in
    virtual reality. This package cause all the python servers to be installed.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-protocol
