package:
  name: narupa-lammps
  version: {{ NARUPA_BUILD_VERSION }}

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools
    - cython
    - numpy

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - narupa-core =={{ NARUPA_BUILD_VERSION }}
    - numpy
    - cython
    #- mpi4py

about:
  home: https://narupa.readthedocs.io
  license: GPL-3
  license_file: {{ NARUPA_LICENSE_PATH }}
  summary: LAMMPS bindings for Narupa.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides LAMMPS bindings and servers for
    Narupa.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-protocol
