package:
  name: narupa-core
  version: {{ os.environ["NARUPA_BUILD_VERSION"] }}

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - narupa-multiplayer = narupa.multiplayer.cli:main

requirements:
  build:
    - python >={{ MIN_PYTHON_VERSION }}
    - setuptools
    - grpcio-tools

  run:
    - python >={{ MIN_PYTHON_VERSION }}
    - typing-extensions
    - protobuf
    - grpcio
    - numpy
    - narupa-essd =={{ NARUPA_BUILD_VERSION }}

about:
  home: https://narupa.readthedocs.io
  license: GPL-3
  license_file: {{ NARUPA_LICENSE_PATH }}
  summary: Core modules to use the Narupa python library.
  description: |
    Narupa is a framework for interactive molecular dynamics simulation in
    virtual reality. This package provides the core components to write a
    server or a client program in python.
  doc_url: https://narupa.readthedocs.io
  dev_url: https://gitlab.com/intangiblerealities/narupa-protocol
